version: "3.9"

services:
  postgres-auth:
    image: postgres:15
    container_name: postgres-auth
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: bondy-auth
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
    volumes:
      - postgres_auth_data:/var/lib/postgresql/data

  postgres-interaction:
    image: postgres:15
    container_name: postgres-interaction
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: bondy-interaction
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
    volumes:
      - postgres_interaction_data:/var/lib/postgresql/data

  postgres-communication:
    image: postgres:15
    container_name: postgres-communication
    restart: always
    ports:
      - "5434:5432"
    environment:
      POSTGRES_DB: bondy-communication
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
    volumes:
      - postgres_communication_data:/var/lib/postgresql/data

volumes:
  postgres_auth_data:
  postgres_interaction_data:
  postgres_communication_data: