spring:
  application:
    name: communication-service
  config:
    import: optional:configserver:http://localhost:8888

logging:
  level:
    org.springframework.messaging: DEBUG
    org.springframework.web.socket: DEBUG
    org.springframework.web.socket.messaging: DEBUG
    org.example.communicationservice.config.websocket: DEBUG
